name: Convert DOCX to PDF

on:
  push:
    paths:
      - '*.docx'

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # 选择你想要使用的 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install docx2pdf

    - name: Convert DOCX to PDF
      run: |
        for file in *.docx; do
          docx2pdf "$file"
        done

    - name: Upload PDF files
      uses: actions/upload-artifact@v2
      with:
        name: pdf-files
        path: |
          *.pdf
