name: Convert Word to PDF

on:
  push:
    branches:
      - main


jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pandoc and texlive-xetex
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-latex-extra texlive-xetex

      - name: Convert Word to PDF
        run: |
          pandoc proposal.docx -o proposal.pdf --pdf-engine=xelatex --pdf-engine-opt=-shell-escape
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.test }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.test }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./proposal.pdf
          asset_name: proposal.pdf
          asset_content_type: application/pdf
